# Generated by Django 4.1.3 on 2022-11-24 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
        ('vehiculo', '0002_vehiculo_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.persona'),
        ),
    ]
